version: '3'

volumes:
  web-storage:

services:
  web:
    build: ..
    ports:
      - 8000:80
    
    volumes:
      - web-storage:/usr/src/app

  db:
    image: postgres
    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: chat_user
      POSTGRES_DB: chat
