"""create table token

Revision ID: 4d7acf27072a
Revises: 38fad8233beb
Create Date: 2021-12-19 13:13:01.968698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7acf27072a'
down_revision = '38fad8233beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_date', sa.DateTime(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_token_uid'), 'token', ['uid'], unique=False)
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_token_uid'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
