"""First

Revision ID: f50b326bc1d2
Revises: 
Create Date: 2021-11-22 22:10:39.144782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50b326bc1d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_dialog_uid'), 'dialog', ['uid'], unique=False)
    op.create_table('user',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_uid'), 'user', ['uid'], unique=False)
    op.create_table('message',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('readed', sa.Boolean(), nullable=True),
    sa.Column('dialog_id', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.uid'], ),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialog.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_message_uid'), 'message', ['uid'], unique=False)
    op.create_table('user_dialog',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('dialog_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialog.uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_dialog_uid'), 'user_dialog', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dialog_uid'), table_name='user_dialog')
    op.drop_table('user_dialog')
    op.drop_index(op.f('ix_message_uid'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_user_uid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_dialog_uid'), table_name='dialog')
    op.drop_table('dialog')
    # ### end Alembic commands ###
